---

- name: config hba
  template: >
    src=pg_hba.conf.j2
    dest=/etc/postgresql/{{ elao_postgresql_version }}/main/pg_hba.conf
  notify:
    - postgresql server restart
  sudo: yes
  register: postgresql_config

# Instantly restart postgresql service for coming roles
- name: restart
  service: >
    name=postgresql
    state=restarted
    enabled=yes
  sudo: yes
  when: postgresql_config.changed
