---

- name: databases
  postgresql_db: >
    name={{ item.name }}
    login_user={{ elao_postgresql_login_user }}
    login_password={{ elao_postgresql_login_password }}
    login_host={{ elao_postgresql_login_host }}
    state=present
  with_items: elao_postgresql_databases
  when: elao_postgresql_databases|length > 0
