---

- name: repositories key
  apt_key: >
    url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state=present
  sudo: yes

- name: repositories
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main
  sudo: yes

- name: packages
  apt: >
    name={{ item }}
    state=present
  with_items:
    - postgresql-9.3
    - python-psycopg2
  sudo: yes

- name: config user
  lineinfile: >
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    line="local all all trust"
    state=present
    regexp="^local all all trust$"
    insertbefore="^# DO NOT DISABLE!"
  notify:
    - postgresql server restart
  sudo: yes
  register: postgresql_config

- name: restart
  service: >
    name=postgresql
    state=restarted
    enabled=yes
  sudo: yes
  when: postgresql_config.changed

- name: user
  postgresql_user: >
    name=root
    role_attr_flags=SUPERUSER,CREATEROLE,CREATEDB,REPLICATION
    state=present

- name: service
  service: >
    name=postgresql
    state=started
    enabled=yes
  sudo: yes
