---

- name: config user
  lineinfile: >
    dest=/etc/postgresql/{{ elao_postgresql_version }}/main/pg_hba.conf
    line="local all all trust"
    state=present
    regexp="^local all all trust$"
    insertbefore="^# DO NOT DISABLE!"
  notify:
    - postgresql server restart
  sudo: yes
  register: postgresql_config

- name: restart
  service: >
    name=postgresql
    state=restarted
    enabled=yes
  sudo: yes
  when: postgresql_config.changed

- name: user
  postgresql_user: >
    name=root
    role_attr_flags=SUPERUSER,CREATEROLE,CREATEDB,REPLICATION
    state=present
